# vim: ts=2:sw=2:et
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.name" . }}-deny-all
  labels:
    component: {{ include "common.name" . }}
    app: {{ include "common.name" . }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  ingress: []
  egress: []
  podSelector:
    matchLabels:
      component: {{ include "common.name" . }}
      tier: backend
