# vim: ts=2:sw=2:et
{{- if .Values }}
  {{- if .Values.global }}
    {{- if .Values.global.secret }}
      {{- if (not (lookup "v1" "Secret" .Release.Namespace .Values.global.secret)) }}
        {{- $serviceAccountName := .Values.estap.secretWriterServiceAccountName | default "estap-secret-writer" }}
        {{- if not (lookup "v1" "ServiceAccount" .Release.Namespace $serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}
  labels:
    component: {{ .Values.estap.name }}
    app: {{ .Values.estap.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret-account
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
