# vim: ts=2:sw=2:et
{{- if .Values }}
  {{- if .Values.global }}
    {{- if .Values.global.secret }}
      {{- if not .Values.global.dontMakeServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}
  labels:
    component: {{ include "common.name" . }}
    app: {{ include "common.name" . }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret-account
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
