# vim: ts=2:sw=2:et
{{- if .Values }}
  {{- if .Values.global }}
    {{- if .Values.global.secret }}
      {{- if (not (lookup "v1" "Secret" .Release.Namespace .Values.global.secret)) }}
kind: Job
apiVersion: batch/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.name" . }}-create-secret-job
  labels:
    component: {{ .Values.estap.name }}
    app: {{ .Values.estap.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret
spec:
    template:
      metadata:
        labels:
          run: {{ include "common.name" . }}-create-secret-job
      spec:
        volumes:
        - emptyDir: {}
          name: metastore-volume
        serviceAccountName: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}
    {{- if .Values.global }}
      {{- if .Values.global.imagePullSecret }}
        imagePullSecrets:
          - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
    {{- end }}
        initContainers:
        - name: estap-create-secret-job-cert-gen
          volumeMounts:
          - mountPath: /tmp/metastore
            name: metastore-volume
          image: {{ include "estap-deploy.estap.registryImageTag" . }}
          args: ['gpctl genca > /tmp/metastore/ca.pem && gpctl gen_csr && mv /var/log/gp/key.tmp.pem /tmp/metastore/tls.key && gpctl -A/tmp/metastore/ca.pem -R/var/log/gp/csr.tmp.pem sign_csr > /tmp/metastore/tls.crt && rm -f /var/log/gp/csr.tmp.pem' ]
          command:
          - /bin/sh
          - '-c'
          imagePullPolicy: {{ include "estap-deploy.estap.imagePullPolicy" . }}
        containers:
        - name: estap-create-secret-job
          volumeMounts:
          - mountPath: /tmp/metastore
            name: metastore-volume
          image: {{ include "estap-deploy.estap.registryImageTag" . }}
          args: ["env && kubectl create secret generic {{ .Values.global.secret }} --from-file=ca.pem=/tmp/metastore/ca.pem --from-file=tls.key=/tmp/metastore/tls.key --from-file=tls.crt=/tmp/metastore/tls.crt"]
          command:
          - /bin/sh
          - '-c'
          imagePullPolicy: {{ include "estap-deploy.estap.imagePullPolicy" . }}
        restartPolicy: OnFailure
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
