# vim: ts=2:sw=2:et
{{- if .Values }}
  {{- if .Values.global }}
    {{- if .Values.global.secret }}
      {{- if and (not .Values.global.dontMakeRole) (not .Values.global.dontMakeServiceAccount) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}-role
  labels:
    component: {{ include "common.name" . }}
    app: {{ include "common.name" . }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret-account-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch"]
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
