# vim: ts=2:sw=2:et
{{- if .Values.global.secret }}
  {{- if (not (lookup "v1" "Secret" .Release.Namespace .Values.global.secret)) }}
    {{- $serviceAccountName := .Values.estap.secretWriterServiceAccountName | default "estap-secret-writer" }}
    {{- $serviceAccountRoleName := printf "%s-%s" $serviceAccountName "role" }}
    {{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace $serviceAccountRoleName ) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}-role
  labels:
    component: {{ .Values.estap.name }}
    app: {{ .Values.estap.name }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret-account-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update"]
    {{- end }}
  {{- end }}
{{- end }}
