# vim: ts=2:sw=2:et
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.name" . }}
  labels:
    component: {{ .Values.estap.name }}
    app: {{ .Values.estap.name }}
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ include "estap-deploy.estap.replicas" . }}
  selector:
    matchLabels:
      component: {{ .Values.estap.name }}
      app: {{ .Values.estap.name }}
      tier: backend
  template:
    metadata:
      labels:
        component: {{ .Values.estap.name }}
        app: {{ .Values.estap.name }}
        tier: backend
        {{- include "common.labels" . | nindent 8 }}
    spec:
      volumes:
      - emptyDir: {}
        name: metastore-volume
      - emptyDir: {}
        name: ephemeral
      - name: dshm
        emptyDir: 
          medium: Memory
          sizeLimit: 500Mi
{{- if .Values.global }}
  {{- if .Values.global.secret }}
      - name: estap-secret
        secret:
          secretName: {{ .Values.global.secret }}
  {{- end }}
  {{- if .Values.global.volumeName }}
      - name: pv
        persistentVolumeClaim:
          claimName: {{ .Values.global.volumeName }}
  {{- end }}
{{- end }}
      serviceAccountName: {{ include "estap-deploy.estap.serviceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      hostIPC: false
      hostNetwork: false
      hostPID: false
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ include "estap-deploy.estap.uid" . }}
        fsGroup: {{ include "estap-deploy.estap.fsGroup" . }}
        supplementalGroups: [ {{ include "estap-deploy.estap.supplementalGroups" . }} ]
{{- if .Values.global }}
  {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
  {{- end }}
  {{- if .Values.global.secret }}
      initContainers:
      - args: ["head -c -1 -q /etc/estap-ssl/tls.crt /etc/estap-ssl/tls.key > /tmp/metastore/estap.pem"]
        command:
        - /bin/sh
        - '-c'
        name: add-cert
        image: {{ include "estap-deploy.estap.registryImageTag" . }}
        imagePullPolicy: {{ include "estap-deploy.estap.imagePullPolicy" . }}
        volumeMounts:
        - mountPath: /etc/estap-ssl
          name: estap-secret
        - mountPath: /tmp/metastore
          name: metastore-volume
        securityContext:
          {{- include "estap-deploy.container.securityContext" . | nindent 10 }}
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 100m
            memory: 512Mi
  {{- end }}
{{- end }}
      containers:
      - imagePullPolicy: {{ include "estap-deploy.estap.imagePullPolicy" . }}
        name: {{ include "common.name" . }}
        image: {{ include "estap-deploy.estap.registryImageTag" . }}
        livenessProbe:
          exec:
            command:
            - {{ include "estap-deploy.estap.livenessProbe.command" . }}
          periodSeconds: {{ include "estap-deploy.estap.livenessProbe.periodSeconds" . }}
          failureThreshold: {{ include "estap-deploy.estap.livenessProbe.failureThreshold" . }}
          initialDelaySeconds: {{ include "estap-deploy.estap.livenessProbe.initialDelaySeconds" . }}
        readinessProbe:
          exec:
            command:
            - {{ include "estap-deploy.estap.readinessProbe.command" . }}
          periodSeconds: {{ include "estap-deploy.estap.readinessProbe.periodSeconds" . }}
          failureThreshold: {{ include "estap-deploy.estap.readinessProbe.failureThreshold" . }}
          initialDelaySeconds: {{ include "estap-deploy.estap.readinessProbe.initialDelaySeconds" . }}
        env:
          - name: container
            value: docker
{{- if .Values.estap.override_server_ip }}
          - name: STAP_CONFIG_TAP_TAP_IP
            value: {{ .Values.estap.override_server_ip }}
          - name: STAP_CONFIG_TAP_PRIVATE_TAP_IP
            value: "NULL"
          - name: STAP_CONFIG_TAP_FORCE_SERVER_IP
            value: "1"
{{- else }}
          - name: STAP_CONFIG_TAP_TAP_IP
            value: "NULL"
{{- end }}
          - name: STAP_CONFIG_PARTICIPATE_IN_LOAD_BALANCING
            value: {{ include "estap-deploy.estap.participate_in_load_balancing" . | quote }}
          - name: STAP_CONFIG_PROXY_GROUP_MEMBER_COUNT
            value: {{ include "estap-deploy.estap.replicas" . | quote }}
          - name: STAP_CONFIG_PROXY_GROUP_UUID
            valueFrom:
              configMapKeyRef:
                name: {{ include "common.name" . }}-configmap
                key: uuid
{{- if .Values.estap.verify_guardium }}
          - name: STAP_CONFIG_SQLGUARD_CERT_CN
            value: {{ .Values.estap.verify_guardium.cn }}
          - name: STAP_CONFIG_GUARDIUM_CA_PATH
            value: {{ include "estap-deploy.estap.verify_guardium.ca_path" . }}
{{- end }}
          - name: STAP_CONFIG_PROXY_DEBUG
            value: {{ include "estap-deploy.estap.proxy.debug" . | quote }}
          - name: STAP_CONFIG_PROXY_NUM_WORKERS
            value: {{ include "estap-deploy.estap.proxy.num_workers" . | quote }}
          - name: STAP_CONFIG_PROXY_PROXY_PROTOCOL
            value: {{ include "estap-deploy.estap.proxy.proxy_protocol" . | quote }}
          - name: STAP_CONFIG_PROXY_DISCONNECT_ON_INVALID_CERTIFICATE
            value: {{ include "estap-deploy.estap.proxy.disconnect_on_invalid_certificate" . | quote }}
          - name: STAP_CONFIG_PROXY_NOTIFY_ON_INVALID_CERTIFICATE
            value: {{ include "estap-deploy.estap.proxy.notify_on_invalid_certificate" . | quote }}
          - name: STAP_CONFIG_PROXY_LISTEN_PORT
            value: {{ include "estap-deploy.estap.proxy.listen_port" . | quote }}
{{- if .Values.global }}
  {{- if .Values.global.secret }}
    {{- if .Values.estap.proxy }}
      {{- if .Values.estap.proxy.secret }}
          - name: STAP_CONFIG_PROXY_SECRET
            valueFrom:
              secretKeyRef:
                name: estap-secret
                key: {{ .Values.estap.proxy.secret }}
        {{- if .Values.estap.proxy.csr }}
          {{- with .Values.estap.proxy.csr }}
          - name: STAP_CONFIG_PROXY_CSR_NAME
            value: {{ .name }}
            {{- if .country }}
          - name: STAP_CONFIG_PROXY_CSR_COUNTRY
            value: {{ .country }}
            {{- end }}
            {{- if .province }}
          - name: STAP_CONFIG_PROXY_CSR_PROVINCE
            value: {{ .province }}
            {{- end }}
            {{- if .city }}
          - name: STAP_CONFIG_PROXY_CSR_CITY
            value: {{ .city }}
            {{- end }}
            {{- if .organization }}
          - name: STAP_CONFIG_PROXY_CSR_ORGANIZATION
            value: {{ .organization }}
            {{- end }}
            {{- if .keylength }}
          - name: STAP_CONFIG_PROXY_CSR_KEYLENGTH
            value: {{ .keylength | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- else }}
          - name: STAP_CONFIG_PROXY_PEM_PATH
            value: /tmp/metastore/estap.pem
      {{- end }}
    {{- else }}
        - name: STAP_CONFIG_PROXY_PEM_PATH
          value: /tmp/metastore/estap.pem
    {{- end }}
  {{- end }}
{{- end }}
          - name: STAP_CONFIG_PROXY_DB_HOST
            value: {{ .Values.estap.db.host | quote }}
          - name: STAP_CONFIG_DB_0_REAL_DB_PORT
            value: {{ include "estap-deploy.estap.db.port" . | quote }}
          - name: STAP_CONFIG_DB_0_DB_TYPE
            value: {{ .Values.estap.db.type | quote }}
          - name: STAP_CONFIG_SQLGUARD_0_SQLGUARD_IP
            value: {{ .Values.estap.guardium.host | quote }}
          - name: STAP_CONFIG_SQLGUARD_0_PRIMARY
            value: "1"
{{- if .Values.estap.guardium.port }}
          - name: STAP_CONFIG_SQLGUARD_0_SQLGUARD_PORT
            value: {{ .Values.estap.guardium.port | quote }}
{{- end }}
{{- if .Values.estap.guardium.connection_pool_size }}
          - name: STAP_CONFIG_SQLGUARD_0_CONNECTION_POOL_SIZE
            value: {{ .Values.estap.guardium.connection_pool_size | quote }}
{{- end }}
{{- if .Values.estap.guardium.num_main_thread }}
          - name: STAP_CONFIG_SQLGUARD_0_NUM_MAIN_THREAD
            value: {{ .Values.estap.guardium.num_main_thread | quote }}
{{- end }}
{{- if .Values.estap.guardium.secondaries }}
  {{- if $.Values.estap.guardium.secondaries }}
    {{- with $.Values.estap.guardium.secondaries }}
      {{- if .s1 }}
        {{- with .s1 }}
          {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_1_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_1_PRIMARY
            value: "2"
            {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_1_SQLGUARD_PORT
            value: {{ .port | quote }}
            {{- end }}
            {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_1_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
            {{- end }}
            {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_1_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if .s2 }}
          {{- with .s2 }}
            {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_2_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_2_PRIMARY
            value: "3"
              {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_2_SQLGUARD_PORT
            value: {{ .port | quote }}
              {{- end }}
              {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_2_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
              {{- end }}
              {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_2_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .s3 }}
            {{- with .s3 }}
              {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_3_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_3_PRIMARY
            value: "4"
                {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_3_SQLGUARD_PORT
            value: {{ .port | quote }}
                {{- end }}
                {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_3_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                {{- end }}
                {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_3_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- if .s4 }}
              {{- with .s4 }}
                {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_4_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_4_PRIMARY
            value: "5"
                  {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_4_SQLGUARD_PORT
            value: {{ .port | quote }}
                  {{- end }}
                  {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_4_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                  {{- end }}
                  {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_4_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- if .s5 }}
                {{- with .s5 }}
                  {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_5_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_5_PRIMARY
            value: "6"
                    {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_5_SQLGUARD_PORT
            value: {{ .port | quote }}
                    {{- end }}
                    {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_5_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                    {{- end }}
                    {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_5_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                    {{- end }}
                  {{- end }}
                {{- end }}
                {{- if .s6 }}
                  {{- with .s6 }}
                    {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_6_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_6_PRIMARY
            value: "7"
                      {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_6_SQLGUARD_PORT
            value: {{ .port | quote }}
                      {{- end }}
                      {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_6_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                      {{- end }}
                      {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_6_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                      {{- end }}
                    {{- end }}
                  {{- end }}
                  {{- if .s7 }}
                    {{- with .s7 }}
                      {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_7_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_7_PRIMARY
            value: "8"
                        {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_7_SQLGUARD_PORT
            value: {{ .port | quote }}
                        {{- end }}
                        {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_7_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                        {{- end }}
                        {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_7_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                        {{- end }}
                      {{- end }}
                    {{- end }}
                    {{- if .s8 }}
                      {{- with .s8 }}
                        {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_8_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_8_PRIMARY
            value: "9"
                          {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_8_SQLGUARD_PORT
            value: {{ .port | quote }}
                          {{- end }}
                          {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_8_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                          {{- end }}
                          {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_8_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                          {{- end }}
                        {{- end }}
                      {{- end }}
                      {{- if .s9 }}
                        {{- with .s9 }}
                          {{- if .host}}
          - name: STAP_CONFIG_SQLGUARD_9_SQLGUARD_IP
            value: {{ .host | quote }}
          - name: STAP_CONFIG_SQLGUARD_9_PRIMARY
            value: "10"
                            {{- if .port}}
          - name: STAP_CONFIG_SQLGUARD_9_SQLGUARD_PORT
            value: {{ .port | quote }}
                            {{- end }}
                            {{- if .connection_pool_size}}
          - name: STAP_CONFIG_SQLGUARD_9_CONNECTION_POOL_SIZE
            value: {{ .connection_pool_size | quote }}
                            {{- end }}
                            {{- if .num_main_thread}}
          - name: STAP_CONFIG_SQLGUARD_9_NUM_MAIN_THREAD
            value: {{ .num_main_thread | quote }}
                            {{- end }}
                          {{- end }}
                        {{- end }}
                      {{- end }}
                    {{- end }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
        ports:
          - containerPort: 8080
            protocol: "TCP"
            name: "http"
          - containerPort: {{ include "estap-deploy.estap.proxy.listen_port" . }}
            protocol: "TCP"
            name: "db"
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /tmp
            name: ephemeral
            subPath: tmp
          - mountPath: /var/log/supervisord
            name: ephemeral
            subPath: supervisord_log
          - mountPath: /var/log/gp
            name: ephemeral
            subPath: gp_log
          - mountPath: /var/run/supervisord
            name: ephemeral
            subPath: run_supervisord
          - mountPath: /var/run/gp
            name: ephemeral
            subPath: run_gp
          - mountPath: /usr/local/guardium
            name: ephemeral
            subPath: usr/local/guardium
          - mountPath: /etc/supervisor.d
            name: ephemeral
            subPath: etc/supervisor.d
          - mountPath: /etc/gp
            name: ephemeral
            subPath: etc/gp
          - mountPath: /tmp/metastore
            name: metastore-volume
{{- if .Values.global }}
  {{- if .Values.global.volumeName }}
          - mountPath: "/persistent"
            name: pv
  {{- end }}
{{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: {{ include "estap-deploy.estap.requests.cpu" . }}
            memory: {{ include "estap-deploy.estap.requests.memory" . }}
          limits:
            cpu: {{ include "estap-deploy.estap.limits.cpu" . }}
            memory: {{ include "estap-deploy.estap.limits.memory" . }}
