# vim: ts=2:sw=2:et
{{- if .Values }}
  {{- if .Values.global }}
    {{- if .Values.global.secret }}
      {{- if and (not .Values.global.dontMakeRoleBinding) (not .Values.global.dontMakeServiceAccount) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}-rolebinding
  labels:
    component: {{ include "common.name" . }}
    app: {{ include "common.name" . }}
    {{- include "common.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: external-stap-inheritable-secret-account-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "estap-deploy.global.secretWriterServiceAccountName" . }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
