# vim: ts=2:sw=2:et
{{- if .Values.estap.route }}
{{- if .Values.estap.route.name }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "common.name" . }}-route
  labels:
    app: {{ include "common.name" . }}
    component: {{ include "common.name" . }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ include "common.name" . }}
spec:
  host: {{ include "common.name" . }}.{{ .Values.estap.route.name }}
  port:
    targetPort: {{ include "estap-deploy.estap.proxy.listen_port" . }}
  tls:
{{- if .Values.estap.route }}
{{- if .Values.estap.route.tls }}
{{- if .Values.estap.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.estap.route.tls.insecureEdgeTerminationPolicy }}
{{- end }}
{{- if .Values.estap.route.tls.termination }}
    termination: {{ .Values.estap.route.tls.termination }}
{{- end }}
{{- end }}
{{- end }}
  to:
    kind: Service
    name: {{ include "common.name" . }}-lb
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- end }}
